version: '3'
services:
  data-container:
    build: 
      context : ./data
      dockerfile: Dockerfile.data
    volumes:
      - db-volume:/app

  backend:
    build: 
      context: ./src
      dockerfile: Dockerfile.backend
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - db-volume:/home/app/data
    healthcheck:
      test: "curl -f http://localhost:5000/popularity"
      interval: 5s
      timeout: 600s
      retries: 5


  frontend:
    build: 
      context: ./dashboard
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_healthy

  webscrape:
    build:
      context: ./webscrape
      dockerfile: Dockerfile.webscrape
    command: ""
    volumes:
      - db-volume:/home/opt/data


volumes:
  db-volume: