version: '3'
services:
  data-container:
    build: ./data
    volumes:
      - db-volume:/app

  backend:
    build: ./src
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - db-volume:/home/app/data


  frontend:
    build: ./dashboard
    ports:
      - "8081:80"

    depends_on:
      - backend


volumes:
  db-volume: