FROM selenium/standalone-chrome:latest

USER root
RUN apt-get update && apt-get install -y python3 python3-pip
RUN python3 -m pip install selenium

WORKDIR /home/app

COPY requirements.txt /home/app

RUN pip install --no-cache-dir -r requirements.txt

COPY . /home/app/

ENTRYPOINT ["python3", "scrape_wrapper.py"]





