# Use busybox as the base image of our data container
FROM busybox

# Make a directory to store all our data 
RUN mkdir /app

# Copy data files over into container
COPY *.csv /app

# Sets the directory with the data files as a volume
VOLUME /app

# Runs the container indefinitely
CMD ["tail", "-f", "/dev/null"]